/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "publish-plugin"

pluginManagement {
	repositories {
		mavenLocal() // Only for testing purposes
		mavenCentral()
		google()
		maven { setUrl("https://plugins.gradle.org/m2/") }
	}
}

@Suppress("UnstableApiUsage")
dependencyResolutionManagement {
	repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
	repositories {
		mavenLocal() // Only for testing purposes
		mavenCentral()
		google()
		maven { setUrl("https://plugins.gradle.org/m2/") }
	}
}

include("plugin")
