name: Github Action - Gradle Plugin Publication

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setupjava@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: io.github.uoxx3
          settings-path: ${{ github.workspace }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle
        run: ./gradlew plugin:build --stacktrace

      - name: Test with Gradle
        run: ./gradlew plugin:functionalTest --stacktrace

      - name: Publish with Gradle
        run: ./gradlew plugin:publishPlugins --stacktrace
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}